In [4]:
import pandas as pd
import numpy as np

In [2]:
# EDA (Exploratory data analysis) key question & mindset

# 1-understanding data
# 2-identify patterns, trends, & anomalies
# 3-check data data quality
# 4-understand feature types
# be curious -> ask why & how
#look for relationships between feature
#document assumption & findings and create EDA report.

#function for EDA report

# 1-data dimension(.shape)
# 2-column types (.dtype) like if numerical column have some text data, we need to fix them
# 3- missing values (.isna().sum())
# 4-summary statistics (.describe())
# 5-unique values & categories (.value_counts)

# Example dataset

# customer transections
# how many missing values are present in each column?
# what is the distribution of product category?
# which products are purchased most frequently?
# are there any outliers in the transection amounts?
# how do purchase amount vary by customer region

# 5 EDA question

# is there any mission data? -> quantity has x missing value
# what is the target variable? -> revenue
# what are the numerical feature? -> revenue, quantity etc
# what is the range pf products? -> 4 types beauty, clothing, etc
# summary statistics (.describe()) -> missing products

# key takeways

# always define goals before starting EDA
# edentify target & feature types early
# use EDA question to guide analysis
# document data quality issues & assumptions

In [4]:
# Desctiptive stats & data distributions 
# key functions for descriptive statistics
# df.describe()  provide statistic data
# df['col'].value_counts()  provide number of value 
# df.quantile(q)  divide dataset into 4 equal quantile, every quantile have 25% data. 
# skewness() left or right skewed
# kurtosis analysis

In [5]:
df = pd.read_csv("./files/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])

In [6]:
df.shape  # verify dataset before analysis

(5000, 12)

In [7]:
# core decriptive statistics
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [8]:
df[["unit_price","revenue"]].describe() # for revenue values

        unit_price      revenue
count  5000.000000  5000.000000
mean    308.418774  1021.955148
std     169.259369   825.584219
min      15.150000    11.210000
25%     161.895000   354.527500
50%     309.890000   796.650000
75%     455.557500  1515.690000
max     599.960000  4119.330000

In [9]:
# quantiles
df["revenue"].quantile([0.25,0.5,0.75])

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [10]:
# identifying skewness
df["revenue"].mean(),df["revenue"].median()  # in this case mean is slightly right sid of the median

(np.float64(1021.955148), 796.65)

In [11]:
df["revenue"].skew() # positive value right skew: if value +ve dataset skewed right side and if value -ve its mean dataset left side skewed

np.float64(1.0017064603000962)

In [12]:
# category -level descriptive statistics. 
df.groupby("product_category")["revenue"].describe() # do different product categories behave differently?

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [13]:
df.groupby("product_category")["revenue"].mean() # find highest category

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [14]:
 # using IQR to understand data spread
Q1=df["revenue"].quantile(0.25)
Q3=df["revenue"].quantile(0.75)
IQR = Q3-Q1
Q1,Q3,IQR
# helps understand normal range
# prepares us for outlier detection
# in this case IQR tells us how much data spread between Q1 and Q3 range

(np.float64(354.5275), np.float64(1515.69), np.float64(1161.1625000000001))

In [15]:
(Q3>Q1) and (IQR>0) # check data is Q3 is greater then to Q1 and IQR is positive, this tells us data is valid

np.True_

In [16]:
# working with datetime & time series data 
# in real world data is provide by time series data 
df = pd.read_csv("./files/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])

In [17]:
df = df.set_index("order_date") #we treat data as time series data

In [18]:
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[ns]', name='order_date', length=5000, freq=None)

In [19]:
# monthly revenue analysis
monthly_revenue = df["revenue"].resample("ME").sum()
monthly_revenue # end of month last date monthly revenue

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [20]:
monthly_revenue.pct_change()  #we convert revenue into percentage

order_date
2022-01-31         NaN
2022-02-28   -0.160450
2022-03-31    0.013387
2022-04-30    0.015595
2022-05-31    0.352391
                ...
2035-05-31    0.201727
2035-06-30   -0.245213
2035-07-31   -0.050021
2035-08-31    0.225950
2035-09-30   -0.831297
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [21]:
monthly_revenue.index.is_monotonic_increasing # verify is index is monotonocaly increasing or is jump find like increase and sudenly decrease

True

In [22]:
print(monthly_revenue.sum(),df["revenue"].sum())
monthly_revenue.sum()<=df["revenue"].sum() # check end of month sum is greater then totao reveue

5109775.74 5109775.74

np.True_

In [1]:
# outlier detection using statistical rules
# outlier are data points that fall outside tha normal range, representing extreme values that can distort the mean & median of dataset
# IQR method
# z-scroe method
# domain driven thresholds

In [5]:
df = pd.read_csv("./files/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])

In [6]:
# IQR method 
Q1 = df["revenue"].quantile(0.25)
Q3 = df["revenue"].quantile(0.75)
IQR = Q3-Q1
lower_bound = Q1-1.5*IQR
upper_bound = Q3+1.5*IQR
outliers_iqr = df[(df["revenue"]<lower_bound) | (df["revenue"]>upper_bound)]
# IQR (Interquatile range): Measure the middle 50% of data. Robust for showed distibutions (like revenue)

In [7]:
outliers_iqr.shape # verification

(67, 12)

In [8]:
outliers_iqr[["revenue","product_category"]].head() #inspect

     revenue product_category
39   3640.56             Home
69   3338.37           Beauty
102  3449.50         Clothing
126  3472.39         Clothing
157  3917.54      Electronics

In [9]:
df = df[(df["revenue"]>=lower_bound) & (df["revenue"]<=upper_bound)]
df.shape

(4933, 12)

In [10]:
# z-score method

In [11]:
from scipy.stats import zscore
df = pd.read_csv("./files/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])
df["revenue_z"] = zscore(df["revenue"])
outliers_z = df[df["revenue_z"].abs()>3]

In [12]:
# Z-score shows how many standard deviations a value is from the mean
# rule:[z]>3->outliers

In [13]:
outliers_z.shape # verification

(26, 13)

In [14]:
df = df[df["revenue_z"].abs()<=3]
df.shape

(4974, 13)

In [15]:
# time series data we use iqr method and for other data we use z-score

In [16]:
# Correlation & Co-variance Analysis
# Measure teh relationship between numerrical variables
# if two variables increase together or decrease together is called positive correlation
# if one increase and other decrease is called negative correlation.

In [17]:
# covariance work with absolute value and it is positive or negative
df = pd.read_csv("./files/ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])
numeric_df = df[["quantity","unit_price","discount","delivery_days","revenue"]]
# covariance matrix
print("\nCovariance:\n",numeric_df.cov())

Covariance:
                   quantity    unit_price   discount  delivery_days  \
quantity          4.082009      0.512237  -0.000881      -0.055733
unit_price        0.512237  28648.733946   0.226823       8.338403
discount         -0.000881      0.226823   0.010283      -0.000122
delivery_days    -0.055733      8.338403  -0.000122       9.943075
revenue        1040.110589  94746.795528 -11.661466      14.172711

                     revenue
quantity         1040.110589
unit_price      94746.795528
discount          -11.661466
delivery_days      14.172711
revenue        681589.302978

In [18]:
# coorelation matrix
# linear correlation betwwen deffirent negative or positve value in percentage
print("\nCorrelation:\n",numeric_df.corr())

Correlation:
                quantity  unit_price  discount  delivery_days   revenue
quantity       1.000000    0.001498 -0.004302      -0.008748  0.623564
unit_price     0.001498    1.000000  0.013215       0.015623  0.678032
discount      -0.004302    0.013215  1.000000      -0.000382 -0.139296
delivery_days -0.008748    0.015623 -0.000382       1.000000  0.005444
revenue        0.623564    0.678032 -0.139296       0.005444  1.000000

In [19]:
numeric_df.corr()["revenue"].sort_values(ascending=False) # focus on revenue relations

revenue          1.000000
unit_price       0.678032
quantity         0.623564
delivery_days    0.005444
discount        -0.139296
Name: revenue, dtype: float64

In [20]:
numeric_df.corr().values.min(),numeric_df.corr().values.max() # veification
# expected: minmam>= -1 maximum<= +1

(np.float64(-0.13929560296730714), np.float64(1.0))

In [21]:
# correlation & covariance is not cosation, cosation mean which specific one variable change due to other

In [22]:
# creating an exploratry data analysis report 
# purpose of EDA Report
# 1- summarize key insight from the data
# 2- highlight data quality issues (improve data qualty)
# 3- identify patters, distributions & relationships
# 4- include tables, figures, & summary statistics
# 5- provide a checklist for further analysis

In [23]:
# Activity Goal
# Draft a 6-8 bullet point summary of your hypothetocal EDA findings for a house prices datasets
# Summary points
# 1 - comments on data quality (result depend on data quality, missing value on specific column or specfic percenatge, we can fill using omdeian if that make sense)
# 2 - feature insights (distribution of fair column right skewed, we can transfoam data to reduced skewed)
# 3 - relationship between different attributes (like square fotage of the house and sale price, one increase other also increase. )
# 4 - Categorical insight (top 3 category of property column cover 80% of the data like commercial, residence, parks)
# 5 - outliers (extreme data point, credit vallue at extreme lier which is outliers)
# 6 - Temporal patterns (time series base pattern, sales tend to increase for specific time like last quater of time)

In [24]:
# key takeaways
# 1 - EDA report  = narrative + visual evidence 
# 2 - use bulet points for clarity
# 3 - include tables figures & key metrics
# 4 - document assumptions, anomalies & next steps

In [25]:
# what is an EDA report 
# 1- A short narrative of data insights (do no overwhelms mean not include 100 of pages report)
# 2 - combines tables, figures, & bullet summaries
# 3 - guides preprocessing & modeling ecisions
# 4 - ensures data quality before ML

In [26]:
# key take away
# 1 - EDA report should be consice + structured
# 2 - use visuals & bullet points for clarity
# 3 - documents issues, insights & next step
# 4 - acts as a bridge between raw data & modeling

In [27]:
# Hands on example 6-8 bullet EDA summary
# 1 - Data quality: Around 8 -10% of records contain missing values in the customers rating column
# 2 - Feature insights: The distribution of the revenue column is highly right skewed indicating that a small number of large orders contribute dis-proportionately to total sales. A long transformation may be benificial before applying machine learning models.
# 3 - Realationships: There is a strong positive correlation (r ~~0.82) between quantity and revenue, confirming that is higher order quantities directly drive higher revenue.
# 4 - Categorical insight: The top three product categories( Electronics, clothing, home) account for over 85% of total orders, indicating a strong concentration of sals in limited number of categories.
# 5 - Outliers / Anomaly: Several extreme outliers were observed in the revenue column, likely representing bulk or corporate orders. These outliers should be investagated rather than removed blindly as they may carry important business value. 
# 6 - Temporal Pattern: Sales show a clear upward trend in the final quarter of the year, suggesting seasonal effects likely droven by promotions, sales events, or increased consumer demand.